name: analyze

on: push

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libprotobuf-c-dev libsqlite3-dev \
          libssl-dev pkg-config protobuf-c-compiler

    - name: initialize
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    - name: autobuild
      uses: github/codeql-action/autobuild@v2

    - name: analyze
      uses: github/codeql-action/analyze@v2
