name: build

on: push

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: >
        sudo apt-get install build-essential libprotobuf-c-dev libsqlite3-dev
        libssl-dev pkg-config protobuf-c-compiler
    - name: build
      run: make
