name: build

on: push

jobs:
  ubuntu:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo apt-get install build-essential libprotobuf-c-dev libsqlite3-dev \
          libssl-dev pkg-config protobuf-c-compiler

    - name: build
      run: make

  macos:
    strategy:
      matrix:
        os: [macos-10.15]
        ssl: [libressl, openssl]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      # Also install make because Xcode provides GNU make 3.81 which is too old
      run: brew install make pkg-config protobuf-c sqlite ${{ matrix.ssl }}

    - name: build
      env:
        # Per the instructions from "brew install"
        PKG_CONFIG_PATH: /usr/local/opt/${{ matrix.ssl }}/lib/pkgconfig
      run: gmake

    - name: run
      # Run with bogus input files
      run: ./sigbak check -p sigbak.c sigbak.c || test $? = 1
